/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import br.com.parg.viacep.ViaCEP;
import br.com.parg.viacep.ViaCEPException;
import model.bean.Aluno;
import model.dao.AlunoDAO;
import java.awt.CardLayout;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Curso;
import model.bean.Responsavel;
import model.dao.CursoDAO;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author rodrygo.matos
 */
public class SistemaDeCadastro extends javax.swing.JFrame {
    /**
     * Creates new form Tela
     */
    public SistemaDeCadastro() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) tableTurma.getModel();
        tableTurma.setRowSorter(new TableRowSorter(modelo));
        
    }
    
    public void readTable(String nomeConsulta){
        DefaultTableModel modelo = (DefaultTableModel) tableTurma.getModel();
        modelo.setNumRows(0);
        CursoDAO cdao = new CursoDAO();
        cdao.show(nomeConsulta);
        
        cdao.show(nomeConsulta).forEach((c) -> {
            modelo.addRow(new Object[]{
                c.getCodCurso(),
                c.getNomeCurso()
            });
        });
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroupSexoProfessor = new javax.swing.ButtonGroup();
        painelPrincipal = new javax.swing.JPanel();
        painelGuiasAluno = new javax.swing.JTabbedPane();
        painelDadosPessoais = new javax.swing.JPanel();
        labelNome = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        labelSexo = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        labelNaturalidade = new javax.swing.JLabel();
        estadoBox = new javax.swing.JComboBox<>();
        cidadeBox = new javax.swing.JComboBox<>();
        labelDataNascimento = new javax.swing.JLabel();
        campoDataNascimento = new javax.swing.JFormattedTextField();
        labelCPF = new javax.swing.JLabel();
        campoCPF = new javax.swing.JTextField();
        labelRG = new javax.swing.JLabel();
        campoRG = new javax.swing.JTextField();
        labelFiliacao = new javax.swing.JLabel();
        labelMae = new javax.swing.JLabel();
        labelPai = new javax.swing.JLabel();
        campoMae = new javax.swing.JTextField();
        campoPai = new javax.swing.JTextField();
        labelTelefone = new javax.swing.JLabel();
        campoTel1 = new javax.swing.JTextField();
        campoTel2 = new javax.swing.JTextField();
        labelEndereco = new javax.swing.JLabel();
        labelRua = new javax.swing.JLabel();
        CampoRua = new javax.swing.JTextField();
        labelN = new javax.swing.JLabel();
        campoNumero = new javax.swing.JTextField();
        labelComplemento = new javax.swing.JLabel();
        campoComplemento = new javax.swing.JTextField();
        labelBairro = new javax.swing.JLabel();
        campoBairro = new javax.swing.JTextField();
        labelEstado = new javax.swing.JLabel();
        campoEstado = new javax.swing.JTextField();
        labelCidade = new javax.swing.JLabel();
        campoCidade = new javax.swing.JTextField();
        labelCEP = new javax.swing.JLabel();
        campoCEP = new javax.swing.JTextField();
        painelDadosEscolares = new javax.swing.JPanel();
        labelEFM = new javax.swing.JLabel();
        botaoRadioEFMC = new javax.swing.JRadioButton();
        botaoRadioEFMI = new javax.swing.JRadioButton();
        labelEM = new javax.swing.JLabel();
        botaoRadioEMC = new javax.swing.JRadioButton();
        botaoRadioEMI = new javax.swing.JRadioButton();
        labelNS = new javax.swing.JLabel();
        botaoRadioNSC = new javax.swing.JRadioButton();
        botaoRadioNSI = new javax.swing.JRadioButton();
        painelDadosProfissionais = new javax.swing.JPanel();
        botaoRadioDP7 = new javax.swing.JRadioButton();
        botaoRadioDP8 = new javax.swing.JRadioButton();
        botaoRadioDP9 = new javax.swing.JRadioButton();
        botaoRadioDP10 = new javax.swing.JRadioButton();
        botaoRadioDP11 = new javax.swing.JRadioButton();
        botaoRadioDP12 = new javax.swing.JRadioButton();
        campoOutro = new javax.swing.JTextField();
        painelDadosResponsavel = new javax.swing.JPanel();
        labelNomeResponsavel = new javax.swing.JLabel();
        campoNomeResponsavel = new javax.swing.JTextField();
        labelCPFResponsavel = new javax.swing.JLabel();
        campoCPFResponsavel = new javax.swing.JTextField();
        labelRGResponsavel = new javax.swing.JLabel();
        campoRGResponsavel = new javax.swing.JTextField();
        botaoProximo = new javax.swing.JButton();
        painelCursoTurma = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCurso1 = new javax.swing.JTable();
        labelNomeCurso = new javax.swing.JLabel();
        campoNomeCurso = new javax.swing.JTextField();
        botaoCurso = new javax.swing.JToggleButton();
        labelTurmaInicio1 = new javax.swing.JLabel();
        campoInicioTurma1 = new javax.swing.JFormattedTextField();
        labelTurmaTermino1 = new javax.swing.JLabel();
        campoFimTurma1 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        botaoCurso1 = new javax.swing.JToggleButton();
        painelConsultaAluno = new javax.swing.JPanel();
        scrollPaneTAluno = new javax.swing.JScrollPane();
        tableAluno = new javax.swing.JTable();
        labelConsultaNomeAluno = new javax.swing.JLabel();
        botaoConsultaAluno = new javax.swing.JButton();
        campoConsultaNomeAluno = new javax.swing.JTextField();
        labelConsultaCPFAluno = new javax.swing.JLabel();
        campoConsultaCPFAluno = new javax.swing.JTextField();
        labelConsultaRGAluno = new javax.swing.JLabel();
        campoConsultaRGAluno = new javax.swing.JTextField();
        labelConsultaMatAluno = new javax.swing.JLabel();
        campoConsultaMatAluno = new javax.swing.JTextField();
        painelConsultaCursoTurma = new javax.swing.JPanel();
        ScrollPaneCurso = new javax.swing.JScrollPane();
        tableCurso = new javax.swing.JTable();
        ScrollPaneTurma = new javax.swing.JScrollPane();
        tableTurma = new javax.swing.JTable();
        consultarCurso = new javax.swing.JButton();
        nomeCursoConsulta = new javax.swing.JLabel();
        consultarTurma = new javax.swing.JButton();
        campoConsultarCurso = new javax.swing.JTextField();
        painelCadastroProfessor = new javax.swing.JPanel();
        labelNomeProf = new javax.swing.JLabel();
        campoNomeProf = new javax.swing.JTextField();
        labemCPFProf = new javax.swing.JLabel();
        campoCPFProf = new javax.swing.JTextField();
        labelRGProf = new javax.swing.JLabel();
        campoRGProf = new javax.swing.JTextField();
        labelCodProf = new javax.swing.JLabel();
        campoCodProf = new javax.swing.JTextField();
        botaoCadastroProf = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioSexoProfessorM = new javax.swing.JRadioButton();
        jRadioSexoProfessorF = new javax.swing.JRadioButton();
        jRadioSexoProfessorO = new javax.swing.JRadioButton();
        barraMenu = new javax.swing.JMenuBar();
        menuCadastrar = new javax.swing.JMenu();
        cadastrarAluno = new javax.swing.JMenuItem();
        cadastrarCursoTurma = new javax.swing.JMenuItem();
        cadastrarProfessor = new javax.swing.JMenuItem();
        menuConsultar = new javax.swing.JMenu();
        menuConsultarAlunos = new javax.swing.JMenuItem();
        menuConsultarCursosTurmas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(430, 600));

        painelPrincipal.setLayout(new java.awt.CardLayout());

        labelNome.setText("Nome");

        campoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeActionPerformed(evt);
            }
        });

        labelSexo.setText("Sexo");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Masculino");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Feminino");

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("Outro");

        labelNaturalidade.setText("Naturalidade");

        estadoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "AC", "AL", "AP", "AM", "BA", "CE", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RP", "SC", "SP", "SE", "TO" }));
        estadoBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoBoxItemStateChanged(evt);
            }
        });
        estadoBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoBoxActionPerformed(evt);
            }
        });

        cidadeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidadeBoxActionPerformed(evt);
            }
        });

        labelDataNascimento.setText("Data de Nascimento");

        campoDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        labelCPF.setText("CPF");

        labelRG.setText("RG");

        campoRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoRGActionPerformed(evt);
            }
        });

        labelFiliacao.setText("Filiação");

        labelMae.setText("Mãe");

        labelPai.setText("Pai");

        labelTelefone.setText("Telefone(s) para Contato");

        labelEndereco.setText("Endereço");

        labelRua.setText("Av./Rua");

        CampoRua.setEditable(false);

        labelN.setText("Nº");

        labelComplemento.setText("Complemento");

        labelBairro.setText("Bairro");

        campoBairro.setEditable(false);

        labelEstado.setText("Estado");

        campoEstado.setEditable(false);

        labelCidade.setText("Cidade");

        campoCidade.setEditable(false);

        labelCEP.setText("CEP");

        campoCEP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCEPFocusLost(evt);
            }
        });

        javax.swing.GroupLayout painelDadosPessoaisLayout = new javax.swing.GroupLayout(painelDadosPessoais);
        painelDadosPessoais.setLayout(painelDadosPessoaisLayout);
        painelDadosPessoaisLayout.setHorizontalGroup(
            painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDadosPessoaisLayout.createSequentialGroup()
                        .addComponent(labelEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 324, Short.MAX_VALUE)
                        .addComponent(labelCidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDadosPessoaisLayout.createSequentialGroup()
                        .addComponent(labelRua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoRua))
                    .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                        .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMae)
                            .addComponent(labelPai))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoPai)
                            .addComponent(campoMae)))
                    .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                        .addComponent(labelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNome, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE))
                    .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                        .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(labelBairro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelFiliacao)
                            .addComponent(labelTelefone)
                            .addComponent(campoTel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                .addGap(207, 207, 207)
                                .addComponent(campoTel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelEndereco)
                            .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDadosPessoaisLayout.createSequentialGroup()
                                    .addGap(205, 205, 205)
                                    .addComponent(labelRG)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(campoRG, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                    .addComponent(labelCPF)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(campoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(labelSexo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton5))
                            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(labelNaturalidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(estadoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cidadeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(labelDataNascimento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                        .addComponent(labelCEP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(labelN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(labelComplemento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoComplemento)))
                .addGap(21, 21, 21))
        );
        painelDadosPessoaisLayout.setVerticalGroup(
            painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSexo)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5))
                .addGap(18, 18, 18)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNaturalidade)
                    .addComponent(estadoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cidadeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDataNascimento)
                    .addComponent(campoDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCPF)
                    .addComponent(labelRG)
                    .addComponent(campoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelFiliacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMae)
                    .addComponent(campoMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPai)
                    .addComponent(campoPai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelTelefone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCEP)
                    .addComponent(labelN)
                    .addComponent(campoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelComplemento)
                    .addComponent(campoComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRua)
                    .addComponent(CampoRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBairro)
                    .addComponent(campoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEstado)
                    .addComponent(campoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCidade)
                    .addComponent(campoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        painelGuiasAluno.addTab("D. Pessoais", painelDadosPessoais);

        labelEFM.setText("Ensino Fundamental Maior");

        buttonGroup2.add(botaoRadioEFMC);
        botaoRadioEFMC.setText("Completo");

        buttonGroup2.add(botaoRadioEFMI);
        botaoRadioEFMI.setText("Incompleto");

        labelEM.setText("Ensino Médio");

        buttonGroup3.add(botaoRadioEMC);
        botaoRadioEMC.setText("Completo");

        buttonGroup3.add(botaoRadioEMI);
        botaoRadioEMI.setText("Incompleto");

        labelNS.setText("Nível Superior");

        buttonGroup4.add(botaoRadioNSC);
        botaoRadioNSC.setText("Completo");

        buttonGroup4.add(botaoRadioNSI);
        botaoRadioNSI.setText("Incompleto");

        javax.swing.GroupLayout painelDadosEscolaresLayout = new javax.swing.GroupLayout(painelDadosEscolares);
        painelDadosEscolares.setLayout(painelDadosEscolaresLayout);
        painelDadosEscolaresLayout.setHorizontalGroup(
            painelDadosEscolaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosEscolaresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosEscolaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEFM)
                    .addComponent(labelEM)
                    .addComponent(labelNS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDadosEscolaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosEscolaresLayout.createSequentialGroup()
                        .addComponent(botaoRadioEFMC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoRadioEFMI))
                    .addGroup(painelDadosEscolaresLayout.createSequentialGroup()
                        .addComponent(botaoRadioEMC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoRadioEMI))
                    .addGroup(painelDadosEscolaresLayout.createSequentialGroup()
                        .addComponent(botaoRadioNSC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoRadioNSI)))
                .addContainerGap(406, Short.MAX_VALUE))
        );
        painelDadosEscolaresLayout.setVerticalGroup(
            painelDadosEscolaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDadosEscolaresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosEscolaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoRadioEFMC)
                    .addComponent(labelEFM)
                    .addComponent(botaoRadioEFMI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDadosEscolaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEM)
                    .addComponent(botaoRadioEMC)
                    .addComponent(botaoRadioEMI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDadosEscolaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNS)
                    .addComponent(botaoRadioNSC)
                    .addComponent(botaoRadioNSI))
                .addContainerGap(514, Short.MAX_VALUE))
        );

        painelGuiasAluno.addTab("D. Escolares", painelDadosEscolares);

        buttonGroup5.add(botaoRadioDP7);
        botaoRadioDP7.setText("Não encontrei emprego ou atividade remunerada");

        buttonGroup5.add(botaoRadioDP8);
        botaoRadioDP8.setText("Somente estudo");

        buttonGroup5.add(botaoRadioDP9);
        botaoRadioDP9.setText("Empregado com carteira assinada");

        buttonGroup5.add(botaoRadioDP10);
        botaoRadioDP10.setText("Empregado sem carteira assinada");

        buttonGroup5.add(botaoRadioDP11);
        botaoRadioDP11.setText("Profissional liberal ou tem próprio negócio");

        buttonGroup5.add(botaoRadioDP12);
        botaoRadioDP12.setText("Outro");

        javax.swing.GroupLayout painelDadosProfissionaisLayout = new javax.swing.GroupLayout(painelDadosProfissionais);
        painelDadosProfissionais.setLayout(painelDadosProfissionaisLayout);
        painelDadosProfissionaisLayout.setHorizontalGroup(
            painelDadosProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosProfissionaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoRadioDP7)
                    .addComponent(botaoRadioDP8)
                    .addComponent(botaoRadioDP9)
                    .addComponent(botaoRadioDP10)
                    .addComponent(botaoRadioDP11)
                    .addGroup(painelDadosProfissionaisLayout.createSequentialGroup()
                        .addComponent(botaoRadioDP12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoOutro, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(366, Short.MAX_VALUE))
        );
        painelDadosProfissionaisLayout.setVerticalGroup(
            painelDadosProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosProfissionaisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoRadioDP7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoRadioDP8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoRadioDP9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoRadioDP10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoRadioDP11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoRadioDP12)
                    .addComponent(campoOutro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(450, Short.MAX_VALUE))
        );

        painelGuiasAluno.addTab("D. Profissionais", painelDadosProfissionais);

        labelNomeResponsavel.setText("Nome");

        labelCPFResponsavel.setText("CPF");

        labelRGResponsavel.setText("RG");

        botaoProximo.setText("Cadastrar");
        botaoProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoProximoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelDadosResponsavelLayout = new javax.swing.GroupLayout(painelDadosResponsavel);
        painelDadosResponsavel.setLayout(painelDadosResponsavelLayout);
        painelDadosResponsavelLayout.setHorizontalGroup(
            painelDadosResponsavelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosResponsavelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosResponsavelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosResponsavelLayout.createSequentialGroup()
                        .addComponent(labelNomeResponsavel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNomeResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDadosResponsavelLayout.createSequentialGroup()
                        .addComponent(labelCPFResponsavel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoCPFResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(labelRGResponsavel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoRGResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botaoProximo))
                .addContainerGap(325, Short.MAX_VALUE))
        );
        painelDadosResponsavelLayout.setVerticalGroup(
            painelDadosResponsavelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosResponsavelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosResponsavelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeResponsavel)
                    .addComponent(campoNomeResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDadosResponsavelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCPFResponsavel)
                    .addComponent(labelRGResponsavel)
                    .addComponent(campoCPFResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoRGResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(botaoProximo)
                .addContainerGap(471, Short.MAX_VALUE))
        );

        painelGuiasAluno.addTab("D. do Responsável", painelDadosResponsavel);

        painelPrincipal.add(painelGuiasAluno, "painelGuiasAluno");

        tableCurso1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableCurso1);

        labelNomeCurso.setText("Nome");

        botaoCurso.setText("Cadastrar");
        botaoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCursoActionPerformed(evt);
            }
        });

        labelTurmaInicio1.setText("Informe o horário de início da aula da turma");

        campoInicioTurma1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        labelTurmaTermino1.setText("Informe o horário de término da aula da turma");

        campoFimTurma1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        jButton1.setText("Consultar");

        botaoCurso1.setText("Cadastrar");
        botaoCurso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCurso1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelCursoTurmaLayout = new javax.swing.GroupLayout(painelCursoTurma);
        painelCursoTurma.setLayout(painelCursoTurmaLayout);
        painelCursoTurmaLayout.setHorizontalGroup(
            painelCursoTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCursoTurmaLayout.createSequentialGroup()
                .addGroup(painelCursoTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painelCursoTurmaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelCursoTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelCursoTurmaLayout.createSequentialGroup()
                                .addComponent(labelNomeCurso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelCursoTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelCursoTurmaLayout.createSequentialGroup()
                                        .addComponent(botaoCurso)
                                        .addGap(139, 139, 139)
                                        .addComponent(jButton1))
                                    .addComponent(campoNomeCurso)))
                            .addGroup(painelCursoTurmaLayout.createSequentialGroup()
                                .addGroup(painelCursoTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTurmaTermino1)
                                    .addComponent(labelTurmaInicio1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(painelCursoTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoFimTurma1)
                                    .addComponent(campoInicioTurma1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(painelCursoTurmaLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(botaoCurso1))
                    .addGroup(painelCursoTurmaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelCursoTurmaLayout.setVerticalGroup(
            painelCursoTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCursoTurmaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCursoTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeCurso)
                    .addComponent(campoNomeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelCursoTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCurso)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCursoTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTurmaInicio1)
                    .addComponent(campoInicioTurma1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCursoTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTurmaTermino1)
                    .addComponent(campoFimTurma1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(botaoCurso1)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        botaoCurso.getAccessibleContext().setAccessibleName("");

        painelPrincipal.add(painelCursoTurma, "painelCursoTurma");

        tableAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPaneTAluno.setViewportView(tableAluno);

        labelConsultaNomeAluno.setText("Nome");

        botaoConsultaAluno.setText("Consultar");

        labelConsultaCPFAluno.setText("CPF");

        labelConsultaRGAluno.setText("RG");

        labelConsultaMatAluno.setText("Matrícula");

        javax.swing.GroupLayout painelConsultaAlunoLayout = new javax.swing.GroupLayout(painelConsultaAluno);
        painelConsultaAluno.setLayout(painelConsultaAlunoLayout);
        painelConsultaAlunoLayout.setHorizontalGroup(
            painelConsultaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConsultaAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelConsultaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelConsultaAlunoLayout.createSequentialGroup()
                        .addComponent(labelConsultaNomeAluno)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelConsultaAlunoLayout.createSequentialGroup()
                        .addGroup(painelConsultaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoConsultaAluno)
                            .addGroup(painelConsultaAlunoLayout.createSequentialGroup()
                                .addGroup(painelConsultaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelConsultaMatAluno)
                                    .addComponent(labelConsultaRGAluno)
                                    .addComponent(labelConsultaCPFAluno))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(painelConsultaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoConsultaRGAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoConsultaMatAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoConsultaCPFAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoConsultaNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(scrollPaneTAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 192, Short.MAX_VALUE))))
        );
        painelConsultaAlunoLayout.setVerticalGroup(
            painelConsultaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConsultaAlunoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(painelConsultaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelConsultaNomeAluno)
                    .addComponent(campoConsultaNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelConsultaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelConsultaCPFAluno)
                    .addComponent(campoConsultaCPFAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelConsultaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelConsultaRGAluno)
                    .addComponent(campoConsultaRGAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelConsultaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelConsultaMatAluno)
                    .addComponent(campoConsultaMatAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoConsultaAluno)
                .addGap(18, 18, 18)
                .addComponent(scrollPaneTAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        painelPrincipal.add(painelConsultaAluno, "painelConsultaAluno");

        painelConsultaCursoTurma.setPreferredSize(new java.awt.Dimension(545, 615));

        tableCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ScrollPaneCurso.setViewportView(tableCurso);

        tableTurma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Total de vagas", "Horário de início", "Horário de termino", "Ano", "Semestre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ScrollPaneTurma.setViewportView(tableTurma);

        consultarCurso.setText("Consultar");
        consultarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarCursoActionPerformed(evt);
            }
        });

        nomeCursoConsulta.setText("Curso");

        consultarTurma.setText("Consultar");

        javax.swing.GroupLayout painelConsultaCursoTurmaLayout = new javax.swing.GroupLayout(painelConsultaCursoTurma);
        painelConsultaCursoTurma.setLayout(painelConsultaCursoTurmaLayout);
        painelConsultaCursoTurmaLayout.setHorizontalGroup(
            painelConsultaCursoTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConsultaCursoTurmaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(painelConsultaCursoTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(consultarTurma)
                    .addComponent(ScrollPaneTurma, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .addGroup(painelConsultaCursoTurmaLayout.createSequentialGroup()
                        .addComponent(nomeCursoConsulta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoConsultarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(consultarCurso))
                    .addComponent(ScrollPaneCurso))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        painelConsultaCursoTurmaLayout.setVerticalGroup(
            painelConsultaCursoTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelConsultaCursoTurmaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelConsultaCursoTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeCursoConsulta)
                    .addComponent(campoConsultarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultarCurso))
                .addGap(18, 18, 18)
                .addComponent(ScrollPaneCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(consultarTurma)
                .addGap(18, 18, 18)
                .addComponent(ScrollPaneTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        painelPrincipal.add(painelConsultaCursoTurma, "painelConsultaCursoTurma");

        labelNomeProf.setText("Nome");

        labemCPFProf.setText("CPF");

        labelRGProf.setText("RG");

        labelCodProf.setText("Código");

        campoCodProf.setEditable(false);

        botaoCadastroProf.setText("Cadastrar");
        botaoCadastroProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastroProfActionPerformed(evt);
            }
        });

        jLabel1.setText("Sexo");

        buttonGroupSexoProfessor.add(jRadioSexoProfessorM);
        jRadioSexoProfessorM.setText("Masculino");
        jRadioSexoProfessorM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioSexoProfessorMActionPerformed(evt);
            }
        });

        buttonGroupSexoProfessor.add(jRadioSexoProfessorF);
        jRadioSexoProfessorF.setText("Feminino");

        buttonGroupSexoProfessor.add(jRadioSexoProfessorO);
        jRadioSexoProfessorO.setText("Outro");
        jRadioSexoProfessorO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioSexoProfessorOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelCadastroProfessorLayout = new javax.swing.GroupLayout(painelCadastroProfessor);
        painelCadastroProfessor.setLayout(painelCadastroProfessorLayout);
        painelCadastroProfessorLayout.setHorizontalGroup(
            painelCadastroProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroProfessorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCadastroProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCadastroProfessorLayout.createSequentialGroup()
                        .addGroup(painelCadastroProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNomeProf)
                            .addComponent(labemCPFProf)
                            .addComponent(labelRGProf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelCadastroProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoNomeProf, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                            .addComponent(campoCPFProf)
                            .addComponent(campoRGProf)))
                    .addGroup(painelCadastroProfessorLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioSexoProfessorM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioSexoProfessorF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioSexoProfessorO))
                    .addGroup(painelCadastroProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelCadastroProfessorLayout.createSequentialGroup()
                            .addComponent(labelCodProf)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(campoCodProf))
                        .addComponent(botaoCadastroProf, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(325, Short.MAX_VALUE))
        );
        painelCadastroProfessorLayout.setVerticalGroup(
            painelCadastroProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroProfessorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCadastroProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNomeProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNomeProf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCadastroProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labemCPFProf)
                    .addComponent(campoCPFProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCadastroProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRGProf)
                    .addComponent(campoRGProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCadastroProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jRadioSexoProfessorM)
                    .addComponent(jRadioSexoProfessorF)
                    .addComponent(jRadioSexoProfessorO))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCadastroProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodProf)
                    .addComponent(campoCodProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoCadastroProf)
                .addContainerGap(440, Short.MAX_VALUE))
        );

        painelPrincipal.add(painelCadastroProfessor, "painelCadastroProfessor");

        menuCadastrar.setText("Cadastrar");

        cadastrarAluno.setText("Cadastrar Aluno");
        cadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarAlunoActionPerformed(evt);
            }
        });
        menuCadastrar.add(cadastrarAluno);
        cadastrarAluno.getAccessibleContext().setAccessibleDescription("");

        cadastrarCursoTurma.setText("Cadastrar Curso e Turma");
        cadastrarCursoTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarCursoTurmaActionPerformed(evt);
            }
        });
        menuCadastrar.add(cadastrarCursoTurma);

        cadastrarProfessor.setText("Cadastrar Professor");
        cadastrarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarProfessorActionPerformed(evt);
            }
        });
        menuCadastrar.add(cadastrarProfessor);

        barraMenu.add(menuCadastrar);

        menuConsultar.setText("Consultar");

        menuConsultarAlunos.setText("Consultar Alunos");
        menuConsultarAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultarAlunosActionPerformed(evt);
            }
        });
        menuConsultar.add(menuConsultarAlunos);

        menuConsultarCursosTurmas.setText("Consultar Cursos/Turmas");
        menuConsultarCursosTurmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultarCursosTurmasActionPerformed(evt);
            }
        });
        menuConsultar.add(menuConsultarCursosTurmas);

        barraMenu.add(menuConsultar);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(painelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cidadeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidadeBoxActionPerformed

    }//GEN-LAST:event_cidadeBoxActionPerformed

    private void estadoBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoBoxActionPerformed

    private void estadoBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_estadoBoxItemStateChanged
         cidadeBox.removeAllItems();
        int idUF = 0;

        switch (estadoBox.getSelectedItem().toString()) {
            case "AC":
                idUF = 12;
                break;
            case "AL":
                idUF = 27;
                break;
            case "AP":
                idUF = 16;
                break;
            case "AM":
                idUF = 13;
                break;
            case "BA":
                idUF = 29;
                break;
            case "CE":
                idUF = 23;
                break;
            case "DF":
                idUF = 53;
                break;
            case "ES":
                idUF = 32;
                break;
            case "GO":
                idUF = 52;
                break;
            case "MA":
                idUF = 21;
                break;
            case "MT":
                idUF = 51;
                break;
            case "MS":
                idUF = 50;
                break;
            case "MG":
                idUF = 31;
                break;
            case "PA":
                idUF = 15;
                break;
            case "PB":
                idUF = 25;
                break;
            case "PR":
                idUF = 41;
                break;
            case "PE":
                idUF = 26;
                break;
            case "PI":
                idUF = 22;
                break;
            case "RJ":
                idUF = 33;
                break;
            case "RN":
                idUF = 24;
                break;
            case "RS":
                idUF = 43;
                break;
            case "RO":
                idUF = 11;
                break;
            case "RR":
                idUF = 14;
                break;
            case "SC":
                idUF = 42;
                break;
            case "SP":
                idUF = 35;
                break;
            case "SE":
                idUF = 28;
                break;
            case "TO":
                idUF = 17;
                break;
            case "":
                idUF = 0;
                break;
        }

        try {
            //URL API IBGE para municipios
            URL url = new URL("https://servicodados.ibge.gov.br/api/v1/localidades/estados/" + idUF + "/municipios");
            
            //JSON retornado para a variável jsonScanner. String criada com o JSON retornado
            Scanner jsonScanner = new Scanner(url.openStream());
            String jsonString = "";
            while (jsonScanner.hasNext()) {
                jsonString += jsonScanner.nextLine();
            }

            //Parsing da String para JSON array. Assim é possível acessar as informações retornadas
            JSONArray jsonarray = new JSONArray(jsonString);
            List municipios = new ArrayList();
            for (int i = 0; i < jsonarray.length(); i++) {
                JSONObject jsonobject = jsonarray.getJSONObject(i);
                municipios.add(jsonobject.getString("nome"));
            }
            
            for (Object municipio : municipios) {
                cidadeBox.addItem(municipio.toString());
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_estadoBoxItemStateChanged

    private void botaoProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoProximoActionPerformed
        Aluno aluno = new Aluno();
        Responsavel responsavel = new Responsavel();
        AlunoDAO alunoDAO = new AlunoDAO();
        if (campoNome.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Nome");
        } else if (campoDataNascimento.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Data de nascimento");
        } else if (campoCPF.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo CPF");
        } else if (campoRG.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo RG");
        } else if (campoMae.getText().trim().equals("") && campoPai.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo com nome da mãe ou do pai");
        } else if (campoTel1.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Telefone");
        } else if (campoCEP.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo CEP");
        } else {
            aluno.setNome(campoNome.getText());
            aluno.setDatNasc(campoDataNascimento.getText());
            aluno.setCPF(campoCPF.getText());
            aluno.setRG(campoRG.getText());
            aluno.setCEP(campoCEP.getText());
            aluno.setFone1(campoTel1.getText());
            aluno.setCidadeNasc(cidadeBox.getSelectedItem().toString());
            aluno.setEstadoNasc(estadoBox.getSelectedItem().toString());
            aluno.setNumResidencia(Integer.parseInt(campoNumero.getText()));
            
            responsavel.setNome(campoNomeResponsavel.getText());
            responsavel.setCPF(campoCPFResponsavel.getText());
            responsavel.setRG(campoRGResponsavel.getText());
            
            aluno.setResponsavel(responsavel);
            
            alunoDAO.save(aluno);
        }
        
        

    }//GEN-LAST:event_botaoProximoActionPerformed

    private void campoRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoRGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoRGActionPerformed

    private void cadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarAlunoActionPerformed
        CardLayout cl = (CardLayout) painelPrincipal.getLayout();
        cl.show(painelPrincipal, "painelGuiasAluno");
    }//GEN-LAST:event_cadastrarAlunoActionPerformed

    private void cadastrarCursoTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarCursoTurmaActionPerformed
        CardLayout cl = (CardLayout) painelPrincipal.getLayout();
        cl.show(painelPrincipal, "painelCursoTurma");
    }//GEN-LAST:event_cadastrarCursoTurmaActionPerformed
    
    private void campoCEPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCEPFocusLost
        if(!campoCEP.getText().equals("")){
        try {
            ViaCEP viacep = new ViaCEP();           
            viacep.buscar(campoCEP.getText().trim());
            campoEstado.setText(viacep.getUf());
            campoCidade.setText(viacep.getLocalidade());
            campoBairro.setText(viacep.getBairro());
            CampoRua.setText(viacep.getLogradouro());
        } catch (ViaCEPException ex) {
            campoEstado.setText("");
            campoCidade.setText("");
            campoBairro.setText("");
            CampoRua.setText("");
            Logger.getLogger(SistemaDeCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
        }else{
            campoEstado.setText("");
            campoCidade.setText("");
            campoBairro.setText("");
            CampoRua.setText("");
        }
    }//GEN-LAST:event_campoCEPFocusLost

    private void menuConsultarCursosTurmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultarCursosTurmasActionPerformed
        CardLayout cl = (CardLayout) painelPrincipal.getLayout();
        cl.show(painelPrincipal, "painelConsultaCursoTurma");
    }//GEN-LAST:event_menuConsultarCursosTurmasActionPerformed

    private void menuConsultarAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultarAlunosActionPerformed
        CardLayout cl = (CardLayout) painelPrincipal.getLayout();
        cl.show(painelPrincipal, "painelConsultaAluno");
    }//GEN-LAST:event_menuConsultarAlunosActionPerformed

    private void consultarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarCursoActionPerformed
        
        readTable(campoConsultarCurso.getText().trim());
    }//GEN-LAST:event_consultarCursoActionPerformed

    private void botaoCurso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCurso1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCurso1ActionPerformed

    private void botaoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCursoActionPerformed
        Curso curso = new Curso();
        CursoDAO cursoDAO = new CursoDAO();
        if (campoNomeCurso.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo com o nome do curso");
        }else{
            curso.setNomeCurso(campoNomeCurso.getText());
            cursoDAO.save(curso);
        }
    }//GEN-LAST:event_botaoCursoActionPerformed

    private void cadastrarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarProfessorActionPerformed
        CardLayout cl = (CardLayout) painelPrincipal.getLayout();
        cl.show(painelPrincipal, "painelCadastroProfessor");
    }//GEN-LAST:event_cadastrarProfessorActionPerformed

    private void botaoCadastroProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastroProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCadastroProfActionPerformed

    private void jRadioSexoProfessorMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioSexoProfessorMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioSexoProfessorMActionPerformed

    private void jRadioSexoProfessorOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioSexoProfessorOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioSexoProfessorOActionPerformed

    private void campoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaDeCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(() -> {
            new SistemaDeCadastro().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoRua;
    private javax.swing.JScrollPane ScrollPaneCurso;
    private javax.swing.JScrollPane ScrollPaneTurma;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton botaoCadastroProf;
    private javax.swing.JButton botaoConsultaAluno;
    private javax.swing.JToggleButton botaoCurso;
    private javax.swing.JToggleButton botaoCurso1;
    private javax.swing.JButton botaoProximo;
    private javax.swing.JRadioButton botaoRadioDP10;
    private javax.swing.JRadioButton botaoRadioDP11;
    private javax.swing.JRadioButton botaoRadioDP12;
    private javax.swing.JRadioButton botaoRadioDP7;
    private javax.swing.JRadioButton botaoRadioDP8;
    private javax.swing.JRadioButton botaoRadioDP9;
    private javax.swing.JRadioButton botaoRadioEFMC;
    private javax.swing.JRadioButton botaoRadioEFMI;
    private javax.swing.JRadioButton botaoRadioEMC;
    private javax.swing.JRadioButton botaoRadioEMI;
    private javax.swing.JRadioButton botaoRadioNSC;
    private javax.swing.JRadioButton botaoRadioNSI;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroupSexoProfessor;
    private javax.swing.JMenuItem cadastrarAluno;
    private javax.swing.JMenuItem cadastrarCursoTurma;
    private javax.swing.JMenuItem cadastrarProfessor;
    private javax.swing.JTextField campoBairro;
    private javax.swing.JTextField campoCEP;
    private javax.swing.JTextField campoCPF;
    private javax.swing.JTextField campoCPFProf;
    private javax.swing.JTextField campoCPFResponsavel;
    private javax.swing.JTextField campoCidade;
    private javax.swing.JTextField campoCodProf;
    private javax.swing.JTextField campoComplemento;
    private javax.swing.JTextField campoConsultaCPFAluno;
    private javax.swing.JTextField campoConsultaMatAluno;
    private javax.swing.JTextField campoConsultaNomeAluno;
    private javax.swing.JTextField campoConsultaRGAluno;
    private javax.swing.JTextField campoConsultarCurso;
    private javax.swing.JFormattedTextField campoDataNascimento;
    private javax.swing.JTextField campoEstado;
    private javax.swing.JFormattedTextField campoFimTurma1;
    private javax.swing.JFormattedTextField campoInicioTurma1;
    private javax.swing.JTextField campoMae;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoNomeCurso;
    private javax.swing.JTextField campoNomeProf;
    private javax.swing.JTextField campoNomeResponsavel;
    private javax.swing.JTextField campoNumero;
    private javax.swing.JTextField campoOutro;
    private javax.swing.JTextField campoPai;
    private javax.swing.JTextField campoRG;
    private javax.swing.JTextField campoRGProf;
    private javax.swing.JTextField campoRGResponsavel;
    private javax.swing.JTextField campoTel1;
    private javax.swing.JTextField campoTel2;
    private javax.swing.JComboBox<String> cidadeBox;
    private javax.swing.JButton consultarCurso;
    private javax.swing.JButton consultarTurma;
    private javax.swing.JComboBox<String> estadoBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioSexoProfessorF;
    private javax.swing.JRadioButton jRadioSexoProfessorM;
    private javax.swing.JRadioButton jRadioSexoProfessorO;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBairro;
    private javax.swing.JLabel labelCEP;
    private javax.swing.JLabel labelCPF;
    private javax.swing.JLabel labelCPFResponsavel;
    private javax.swing.JLabel labelCidade;
    private javax.swing.JLabel labelCodProf;
    private javax.swing.JLabel labelComplemento;
    private javax.swing.JLabel labelConsultaCPFAluno;
    private javax.swing.JLabel labelConsultaMatAluno;
    private javax.swing.JLabel labelConsultaNomeAluno;
    private javax.swing.JLabel labelConsultaRGAluno;
    private javax.swing.JLabel labelDataNascimento;
    private javax.swing.JLabel labelEFM;
    private javax.swing.JLabel labelEM;
    private javax.swing.JLabel labelEndereco;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelFiliacao;
    private javax.swing.JLabel labelMae;
    private javax.swing.JLabel labelN;
    private javax.swing.JLabel labelNS;
    private javax.swing.JLabel labelNaturalidade;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNomeCurso;
    private javax.swing.JLabel labelNomeProf;
    private javax.swing.JLabel labelNomeResponsavel;
    private javax.swing.JLabel labelPai;
    private javax.swing.JLabel labelRG;
    private javax.swing.JLabel labelRGProf;
    private javax.swing.JLabel labelRGResponsavel;
    private javax.swing.JLabel labelRua;
    private javax.swing.JLabel labelSexo;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JLabel labelTurmaInicio1;
    private javax.swing.JLabel labelTurmaTermino1;
    private javax.swing.JLabel labemCPFProf;
    private javax.swing.JMenu menuCadastrar;
    private javax.swing.JMenu menuConsultar;
    private javax.swing.JMenuItem menuConsultarAlunos;
    private javax.swing.JMenuItem menuConsultarCursosTurmas;
    private javax.swing.JLabel nomeCursoConsulta;
    private javax.swing.JPanel painelCadastroProfessor;
    private javax.swing.JPanel painelConsultaAluno;
    private javax.swing.JPanel painelConsultaCursoTurma;
    private javax.swing.JPanel painelCursoTurma;
    private javax.swing.JPanel painelDadosEscolares;
    private javax.swing.JPanel painelDadosPessoais;
    private javax.swing.JPanel painelDadosProfissionais;
    private javax.swing.JPanel painelDadosResponsavel;
    private javax.swing.JTabbedPane painelGuiasAluno;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JScrollPane scrollPaneTAluno;
    private javax.swing.JTable tableAluno;
    private javax.swing.JTable tableCurso;
    private javax.swing.JTable tableCurso1;
    private javax.swing.JTable tableTurma;
    // End of variables declaration//GEN-END:variables
}
